### ISSUE TITLE
02_Fitting.ipynb may not work with latest version of ticktack.

### ISSUE THREAD

**Issue by Jordan-Dennis** [SharmaLlama/ticktack#15]
Hi guys, I've been attempting injection recovery and was planning to use the `SingleFitter` object to determine/optimize the production function so I could subtract away the model from the data and get a better estimate of the signal to noise ratio. However, following the code from this example resulted in the following error:
`emcee: Exception while calling your likelihood function:`
I've had a little bit of a fiddle and re-installed the latest version of `ticktack`, but was not able to proceed. I've marked this as an issue, but I've probably changed something accidentally causing it to break.

**Comment by Jordan-Dennis** [comment]
So I've done some more digging amongst other things and discovered that `JAX` does not take `non-hashable` arguments to `JIT` compiled functions anymore. This seems to be causing problems for the `run_mcmc` function which is passed a `numpy.ndarray` as the initial state. `tuple`s and I think `dict`s are the only things that will pass

**Comment by benjaminpope** [comment]
Yeah Jax can't take devicearrays as Jitted static arguments anymore.

 - @qingyuanzhang3, you have been getting the fitter to run nevertheless? Perhaps this is a version clash?

**Comment by Jordan-Dennis** [comment]
@qingyuanzhang3, pushed the newer version to github which resolved the issue for me. I'm now working on the injection recovery.
