### ISSUE TITLE
try tinygp new version for control points

### ISSUE THREAD

**Issue by benjaminpope** [SharmaLlama/ticktack#18]
https://tinygp.readthedocs.io/en/latest/ beta release is out - I wonder if it is competitive with celerite2 for the control points method

**Comment by benjaminpope** [comment]
@qingyuanzhang3 I think you've done this? Will close if you confirm!

**Comment by qingyuanzhang3** [comment]
On tinygp branch GP regression is written in tinygp. From memory it's slower than celerite2, so we are still using celerite2 on main
