### ISSUE TITLE
solver doesn't register miyake events shorter than a couple of days

### ISSUE THREAD

**Issue by benjaminpope** [SharmaLlama/ticktack#20]
Having a problem where event durations >> the time sampling but of order ~ a few days are simply not translating to spikes. Holding all other parameters fixed but increasing the duration, you find that at a critical duration of about 3.8 d (for oversample 1008) the solver suddenly works and gives the correct output.

I suspect this is something to do with tolerances/step sizes, and can be improved with appropriate dimensionalization/tolerances/choice of different solvers.

Temporary workaround: only do spikes longer than ~ a week.

Long term: figure out what is wrong with the solver!

**Comment by Jordan-Dennis** [comment]
This was tested by both @SharmaLlama and myself and we found that by increasing the tolerance of the solver the events could be detected.
