### ISSUE TITLE
Where do the datasets included in the `data` directory come from

### ISSUE THREAD

**Issue by dfm** [SharmaLlama/ticktack#36]
The source, acknowledgement, and appropriate licensing text should be included with the datasets in the `data` directory.

ref: https://github.com/openjournals/joss-reviews/issues/5084

**Comment by qingyuanzhang3** [comment]
Hi dfm, I have added references for datasets in `data` directory as txt files. Thank you for raising this issue.

**Comment by dfm** [comment]
Thanks @qingyuanzhang3! I think that the added references are ok, but pretty much the bare minimum. If possible I think it would be good to perhaps add a readme to that directory and/or more discussion of this to the docs.

**Comment by dfm** [comment]
Pinging this thread again because I truly don't think it's been resolved, but I don't have permissions to reopen!

**Comment by qingyuanzhang3** [comment]
Hi dfm, thank you for suggesting this. I'll add more information as requested.

**Comment by benjaminpope** [comment]
This has now been added to a docs page `docs.md` and to `src/ticktack/data/README.md` as requested.

**Comment by dfm** [comment]
Perfect! Thanks!!
