### ISSUE TITLE
Clean install raises `UserWarning`

### ISSUE THREAD

**Issue by dfm** [SharmaLlama/ticktack#38]
After the past few commits, `ticktack` now installs properly in a fresh environment, but it still mangles the path because of the non-standard directory packaging configuration. After installing `ticktack` in a fresh `conda` environment:

```bash
mamba create -n ticktack python=3.10
mamba activate ticktack
python -m pip install .
```

importing `ticktack` raises this `UserWarning`:

```python
/opt/homebrew/Caskroom/miniforge/base/envs/ticktack/lib/python3.10/site-packages/hdfdict/__init__.py:36: UserWarning: Module ticktack was already imported from /opt/homebrew/Caskroom/miniforge/base/envs/ticktack/lib/python3.10/site-packages/ticktack/__init__.py, but /Users/dforemanmackey/src/joss/sharmallama/ticktack is being added to sys.path
  import pkg_resources as __pkg_resources
```

I'd recommend rearranging things as discussed in #35.

**Comment by dfm** [comment]
ref: https://github.com/openjournals/joss-reviews/issues/5084

**Comment by benjaminpope** [comment]
I think @Jordan-Dennis's recent merge https://github.com/SharmaLlama/ticktack/commit/b91339582db259a52fdd6a5c7f72c350cf500f98 fixed this and I don't see it on my machine - closing with comment but if you still have a problem reopen and I can debug.
