### ISSUE TITLE
jax new version

### ISSUE THREAD

**Issue by ahessl** [SharmaLlama/ticktack#52]
Jax has a new version. Can you check for conflicts?

**Comment by benjaminpope** [comment]
Hi @ahessl,

Sorry, I was travelling at a conference - I see there were some deprecated features (`jax.config`, and `jnp.is1d`) in the new version of jax that have now been fixed.

The new 1.1.4 version passes all the unit tests now - is it working for you?

Cheers,

Ben

**Comment by ahessl** [comment]
Yup! Thanks much!!
